image: ghcr.io/astral-sh/uv:python3.12-bookworm

clone:
  enabled: false # SonarCloud scanner needs the full history to assign issues properly

definitions:
  services:
    docker:
      memory: 4096
  caches:
    sonar: .sonar/cache # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &unitest
        name: Run unittest
        clone:
          enabled: true
          depth: full
        script:
          - echo "build, test, scan.."
          - uv sync --frozen
          - uv run pytest --cov --cov-report=xml
        artifacts:
          - coverage.xml
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        size: 2x
        caches:
          - sonar
        clone:
          enabled: true
          depth: full
        script:
          - pipe: sonarsource/sonarcloud-scan:2.0.0
            variables:
              EXTRA_ARGS: >
                -Dsonar.projectKey=voice-biometric-service
                -Dsonar.sources=.
                -Dsonar.host.url=https://sonarqube.vinbase.ai
                -Dsonar.login=13fb34ad54a4ffc4500c0d417d4c929212ec354f
                -Dsonar.python.coverage.reportPaths=coverage.xml -X
              SONAR_SCANNER_OPTS: -Xmx2048m
        artifacts:
          - coverage.xml
    - step: &check-quality-gate-sonarcloud
        name: Check the Quality Gate on SonarCloud
        script:
          - apt-get update && apt-get install -y curl jq
          - |
            STATUS=$(curl -s -u "13fb34ad54a4ffc4500c0d417d4c929212ec354f:" \
            "https://sonarqube.vinbase.ai/api/qualitygates/project_status?projectKey=voice-biometric-service" \
            | jq -r '.projectStatus.status')
            if [ "$STATUS" != "OK" ]; then
              echo "Quality gate failed!";
              exit 1;
            fi
            echo "Quality gate passed!"

pipelines:
  branches:
    master:
      - step: *unitest
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
  pull-requests:
    "**":
      - step: *unitest
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
