"""init_database

Revision ID: 9b314d1fd7c9
Revises:
Create Date: 2025-03-19 18:08:36.340324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b314d1fd7c9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### CREATE TABLE projects ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(50), nullable=False),
        sa.Column("description", sa.String(200)),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
    )
    op.create_index("idx_projects_created_at", "projects", ["created_at"])
    op.create_index("idx_projects_name_created_at", "projects", ["name", "created_at"])

    # ### CREATE TABLE user_projects ###
    op.create_table(
        "user_projects",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("project_id", sa.Integer, nullable=False),
        sa.Column("user_id", sa.String(50), nullable=False),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column(
            "is_favorite", sa.Boolean(), server_default=sa.sql.expression.false()
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
    )
    op.create_index("idx_user_projects_created_at", "user_projects", ["created_at"])
    op.create_index("idx_user_projects_project_id", "user_projects", ["project_id"])
    op.create_index("idx_user_projects_user_id", "user_projects", ["user_id"])

    # ### CREATE TABLE api_keys ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("project_id", sa.Integer, nullable=False),
        sa.Column("name", sa.String(50), nullable=False),
        sa.Column("api_key", sa.String(100), nullable=False),
        sa.Column(
            "is_favorite", sa.Boolean(), server_default=sa.sql.expression.false()
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
    )


def downgrade() -> None:
    # ### DROP user_projects ###
    op.drop_index("idx_user_projects_created_at", table_name="user_projects")
    op.drop_index("idx_user_projects_project_id", table_name="user_projects")
    op.drop_index("idx_user_projects_user_id", table_name="user_projects")
    op.drop_table("user_projects")

    # ### DROP projects ###
    op.drop_index("idx_projects_created_at", table_name="projects")
    op.drop_index("idx_projects_name_created_at", table_name="projects")
    op.drop_table("projects")
