[debug]
log_level = 10

[origin]
allowed = ['*']

[metadata]
prefix = '/api/v1/voice-biometrics'
swagger = true

[postgres]
uri = 'postgresql+asyncpg://postgres:1234@localhost:5432/voice_biometrics'
max_overflow = 10
pool_size = 10
echo = false

[redis]
uri = 'redis://localhost:6379'

[passport]
uri = 'https://dev-cloud.vinbase.ai/api/v1/pp/users/user'
