[debug]
log_level = 10

[origin]
allowed = ['*']

[metadata]
prefix = '/api/v1/minitest'
swagger = true

[postgres]
uri = 'postgresql+asyncpg://postgres:1234@localhost:5432/minitest'
max_overflow = 10
pool_size = 10
echo = false

[redis]
uri = 'redis://localhost:6379'

[contraint]
max_clients = 50
max_messages = 500
